import { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { quicksand } from "..";
import Link from "next/link";
import { TextField } from "@mui/material";
import { signIn } from "next-auth/react";
import React from "react";

const Index: NextPage = () => {
  function handleSubmit(e: React.FormEvent) {
    console.log(e);
  }
  function handleSignIn(e: React.MouseEvent<HTMLButtonElement>) {
    e.preventDefault();
    signIn("google", { callbackUrl: '/'});
  }
  return (
    <div className={quicksand.className}>
      <Head>
        <title>Clear</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen lg:grid lg:grid-cols-2">
        <div className="relative h-4/6 lg:h-full">
          <Image
            src="/mobileHeader.png"
            alt=""
            width={1280}
            height={853}
            className="absolute -z-20 h-full border-2 border-white object-cover object-center"
          />
          <span className="absolute bottom-0 right-0 h-full w-full bg-gradient-to-t from-white from-10% to-transparent lg:bg-gradient-to-l" />
          <span className="absolute bottom-0 flex w-full flex-col items-center lg:hidden">
            <Image src="/ClearG.svg" alt="" width={154} height={120} />
          </span>
        </div>
        <div className="flex flex-col items-center space-y-4 py-2 font-semibold lg:hidden">
          <Link
            href="#form"
            className="rounded-md bg-primary-blue px-24 py-4 text-white"
          >
            Entrar
          </Link>
          <Link
            href=""
            className="rounded-md border border-primary-blue px-20 py-2 text-primary-blue"
          >
            Cadastrar
          </Link>
        </div>

        <div
          id="form"
          className="flex h-full flex-col items-center justify-center"
        >
          <Image
            src="/ClearG.svg"
            alt=""
            width={154}
            height={120}
            className="pb-12"
          />
          <form
            onSubmit={(e) => {
              handleSubmit(e);
            }}
            className="flex w-3/4 flex-col space-y-16 sm:w-1/2"
          >
            <div className="space-y-4">
              <div>
                <TextField
                  label="Usuário"
                  variant="outlined"
                  size="small"
                  className="w-full"
                />
              </div>
              <div className="flex flex-col">
                <TextField
                  label="Senha"
                  variant="outlined"
                  size="small"
                  className="w-full"
                />
                <Link href={"/"} className="w-fit self-end">
                  Esqueci minha senha
                </Link>
              </div>
            </div>
            <div className="flex w-3/5 flex-col space-y-2 self-center">
              <button className="w-full rounded-md bg-primary-blue py-2 text-white">
                Entrar
              </button>
              <button
                onClick={(e) => handleSignIn(e)}
                className="w-full rounded-md border border-primary-blue py-2 text-primary-blue"
              >
                <Image
                  src="/google.svg"
                  alt=""
                  className="mr-2 inline"
                  width={32}
                  height={32}
                />
                Entrar com conta Google
              </button>
            </div>
          </form>
        </div>
      </div>

      {/* Login Form */}
      {/* <div id="form" className="relative h-screen py-32">
        <div className="flex flex-col items-center space-y-4">
          <div>
            <Image src="/ClearG.svg" alt="" width={154} height={120} />
            <h1 className="text-xl font-medium text-primary-blue text-center">Login</h1>
          </div>
          <form className="flex flex-col">
            <input type="text" className="border" />
            <input type="text" className="border" />
          </form>
        </div> */}
      {/* Products background */}
      {/* <div className="absolute bottom-0 h-2/4 w-full">
          <div className="relative h-full sm:h-1/2">
            <Image
              src="/loginBottom.jpg"
              alt=""
              width={393}
              height={282}
              className="absolute -z-20 h-full w-full object-cover object-right"
            />
          </div>
          <span className="absolute bottom-0 h-full w-full bg-gradient-to-b from-white from-5% to-transparent" />
          <span className="absolute bottom-0 h-full w-full bg-gradient-to-t from-primary-blue from-5% to-transparent" />
        </div>
      </div> */}
    </div>
  );
};

export default Index;
