import { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { quicksand } from "..";
import Link from "next/link";

const Index: NextPage = () => {
  return (
    <div className={quicksand.className}>
      <Head>
        <title>Clear</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen">
        <div className="relative h-4/6 sm:h-1/2">
          <Image
            src="/mobileHeader.png"
            alt=""
            width={1280}
            height={853}
            className="absolute -z-20 h-full object-cover object-center sm:w-full"
          />
          <span className="absolute bottom-0 h-full w-full bg-gradient-to-t from-white from-5% to-transparent" />
          <span className="absolute bottom-0 flex w-full flex-col items-center">
            <Image src="/ClearG.svg" alt="" width={154} height={120} />
          </span>
        </div>
        <div className="flex flex-col items-center space-y-4 py-2 font-semibold">
          <Link
            href="#form"
            className="rounded-md bg-primary-blue px-24 py-4 text-white"
          >
            Entrar
          </Link>
          <Link
            href=""
            className="rounded-md border border-primary-blue px-20 py-2 text-primary-blue"
          >
            Cadastrar
          </Link>
        </div>
      </div>

      {/* Login Form */}
      <div id="form" className="relative h-screen py-32">
        <div className="flex flex-col items-center space-y-4">
          <div>
            <Image src="/ClearG.svg" alt="" width={154} height={120} />
            <h1 className="text-xl font-medium text-primary-blue text-center">Login</h1>
          </div>
          <form className="flex flex-col">
            <input type="text" className="border" />
            <input type="text" className="border" />
          </form>
        </div>
        {/* Products background */}
        <div className="absolute bottom-0 h-2/4 w-full">
          <div className="relative h-full sm:h-1/2">
            <Image
              src="/loginBottom.jpg"
              alt=""
              width={393}
              height={282}
              className="absolute -z-20 h-full w-full object-cover object-right"
            />
          </div>
          <span className="absolute bottom-0 h-full w-full bg-gradient-to-b from-white from-5% to-transparent" />
          <span className="absolute bottom-0 h-full w-full bg-gradient-to-t from-primary-blue from-5% to-transparent" />
        </div>
      </div>
    </div>
  );
};

export default Index;
